// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pswypdtkrtpmteaggzlt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzd3lwZHRrcnRwbXRlYWdnemx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0NzgxMDUsImV4cCI6MjA1NzA1NDEwNX0.xd7q3qzwWhGGJk4-fYIYXe2Q0GzKaD0ZoJhn2dv-khk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);